### ISSUE TITLE
Unable to complete Mission 15: Crazy Gadget

### ISSUE THREAD

**Issue by DreamShark-Bytes** [SonicFreak94/sa2-action-remap#1]
Your remapping prevented Sonic from rolling under a gap at the start of the mission. 

Maybe you should put your mod on gamebanana so people can more easily give you meaningful feedback. 
Probably broke things earlier in the game - I installed it midway through the Hero story. 

So much for a "better" remap

**Comment by DreamShark-Bytes** [comment]
I'm going to assume this is from one of the default mods in SA2 Mod Manager that is "Instant Spin Dash"

**Comment by michael-fadely** [comment]
Yeah, that would do it. You can try with my [no-somersault mod](https://github.com/michael-fadely/sa2-no-somersault), but it's still a little questionable in Crazy Gadget from what I remember.
